// Generated by CoffeeScript 1.6.3
"use strict";
module.exports = function(settings, nconf, libs) {
  var RSA, RSA_INTERFACE, app, dbox, uuid;
  app = libs.app;
  dbox = require("dbox").app({
    "app_key": "0xdlb1aoqgt4qe2",
    "app_secret": "o44ym3uxlsf0v53"
  });
  uuid = require('node-uuid');
  RSA_INTERFACE = require('./RSA');
  RSA = new RSA_INTERFACE();
  app.get('/keys', function(req, res) {
    return RSA.create(function(ret) {
      ret.uid = uuid.v4().replace(/-/gm, "");
      return res.send(ret);
    });
  });
  return this;
};
