// Generated by CoffeeScript 1.6.3
"use strict";
module.exports = function(settings, nconf, libs) {
  var app, positions, state, uuid;
  app = libs.app;
  uuid = require('node-uuid');
  state = [];
  positions = {};
  app.post('/action', function(req, res) {
    var uid;
    console.log(req.body.type);
    console.log(req.body.velocity);
    if (state.length < 1) {
      state.push({
        type: req.body.type,
        velocity: req.body.velocity
      });
    }
    uid = uuid.v4().replace(/-/gm, "");
    return res.send(uid);
  });
  app.post('/init', function(req, res) {
    state = [];
    return positions = {};
  });
  app.get('/action', function(req, res) {
    return res.send(state.pop());
  });
  app.get('/data', function(req, res) {
    console.log('positions');
    console.log(positions);
    console.log('state');
    console.log(state);
    return res.send(positions);
  });
  app.post('/config/:id', function(req, res) {
    var id;
    id = req.params.id;
    positions[id].screen = {
      width: req.body.width,
      height: req.body.height
    };
    res.send(positions);
    return console.log(positions);
  });
  app.post('/position/:id', function(req, res) {
    var id;
    id = req.params.id;
    positions[id].positions = {
      top: req.body.top,
      left: req.body.left,
      statue: req.body.statue
    };
    return res.send(positions);
  });
  app.get('/positions', function(req, res) {
    return res.send(positions);
  });
  return this;
};
