// Generated by CoffeeScript 1.6.3
"use strict";
module.exports = function(settings, nconf, libs) {
  var app, positions, state, uuid;
  app = libs.app;
  uuid = require('node-uuid');
  state = -1;
  positions = {};
  app.post('/action', function(req, res) {
    var uid;
    console.log('/action');
    // console.log(req.body.velocity);

    var Firebase = require('firebase');
    var myRootRef = new Firebase('https://hackathon234.firebaseio.com/');
    myRootRef.set(state);

    state++;
    
    console.log(state);

    uid = uuid.v4().replace(/-/gm, "");
    return res.send(uid);
  });

  return this;
};
