// Generated by CoffeeScript 1.6.3
"use strict";
module.exports = function(settings, nconf, libs) {
  var app, configs, state, uuid;
  app = libs.app;
  uuid = require('node-uuid');
  state = [];
  configs = {};
  app.post('/action', function(req, res) {
    var uid;
    console.log(req.body.type);
    console.log(req.body.velocity);
    if (state.length < 1) {
      state.push({
        type: req.body.type,
        velocity: req.body.velocity
      });
    }
    uid = uuid.v4().replace(/-/gm, "");
    return res.send(uid);
  });
  app.post('/init', function(req, res) {
    state = [];
    return configs = {};
  });
  app.get('/data', function(req, res) {
    return res.send(state.pop());
  });
  return this;
};
