// Generated by CoffeeScript 1.6.3
"use strict";
module.exports = function(settings, nconf, libs) {
  var app, uuid;
  app = libs.app;
  uuid = require('node-uuid');
  app.get('/keys', function(req, res) {
    var uid;
    uid = uuid.v4().replace(/-/gm, "");
    return res.send(uid);
  });
  return this;
};
